# Generated by Django 3.0.2 on 2020-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
