# Generated by Django 3.0.2 on 2020-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Area_de_Atuação',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
